# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4d7975e4be615c49cb6debd15dba54055d4ac1bec48fa6058b575a8fcced1a444cb7a63f734743ae0303707a14235b2ee9abea46d0572832b9ef393f56d110

test:
  secret_key_base: ad6afc6f1c9a1a99eee95b83a290cb89a5a2487dfd574a6b6e84d71ee66a394eaf6c31f41cc0915cb3f993baf4d9957afbd704bd279c59bf7d6c3563535593ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
